'use client';
import React from 'react';

import { useAIState, useUIState } from '@ai-sdk/rsc';
import { faPenToSquare } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { usePathname, useRouter } from 'next/navigation';

import { AI } from '../../lib/aiProvider';
import WonkyClientError from '../../lib/error/wonkyClientError';
import WonkyErrorBoundary from '../../lib/error/wonkyErrorBoundary';
import WonkBottom from '../layout/wonkBottom';
import WonkTop from '../layout/wonkTop';

import FocusBanner from './answer/focusBanner';
import ChatInput from './ask/chatInput';
import ChatHeader from './chatHeader';

const MainContent = () => {
  const router = useRouter();
  const pathname = usePathname();
  const [aiState] = useAIState<typeof AI>();
  const [messagesUI, _] = useUIState<typeof AI>();

  React.useEffect(() => {
    if (
      // on first response from AI
      pathname === '/chat/new' &&
      aiState.id !== '' // id is set only once the chat has been saved to the db
    ) {
      // reloads the sidebar, which repulls from the db now that the chat has been saved
      router.refresh();
      window.history.pushState({}, '', `/chat/${aiState.id}`);
    }
  }, [aiState.messages, router, aiState.id, pathname]);

  const onNewMessage = () => {
    let newRoute = `/?focus=${aiState.meta.focus.name}`;

    if (aiState.meta.focus.subFocus) {
      newRoute += `&subFocus=${aiState.meta.focus.subFocus}`;
    }

    router.push(newRoute);
  };

  return (
    <>
      {!messagesUI.length ? (
        <>
          <WonkTop>
            <ChatHeader>
              <></>
              {/* Empty children here */}
            </ChatHeader>
          </WonkTop>
          <WonkBottom>
            <WonkyErrorBoundary
              fallback={
                <WonkyClientError
                  thereWasAnErrorLoadingThe='input'
                  type='alert'
                />
              }
            >
              <ChatInput />
            </WonkyErrorBoundary>
            {/* <Disclaimer /> */}
          </WonkBottom>
        </>
      ) : (
        <>
          <WonkTop>
            <FocusBanner focus={aiState.meta.focus} />
            {messagesUI // this is a list of actual React Nodes
              // as generated by our server action submitUserMessage in actions.tsx
              // the first UI node is added on submit in chatInput.tsx
              .map((m) => {
                return (
                  <div key={m.id}>
                    <WonkyErrorBoundary
                      fallback={
                        <WonkyClientError
                          type='alert'
                          thereWasAnErrorLoadingThe='message'
                        />
                      }
                    >
                      {m.display}
                    </WonkyErrorBoundary>
                  </div>
                );
              })}
          </WonkTop>
          <WonkBottom>
            <div className='wonk-chat-width mt-auto'>
              <div className='pt-4'>
                <button
                  className='btn btn-primary'
                  onClick={() => {
                    onNewMessage();
                  }}
                  aria-label='Ask another question'
                >
                  Ask another question{' '}
                  <FontAwesomeIcon className='ms-1' icon={faPenToSquare} />
                </button>
              </div>
            </div>
          </WonkBottom>
        </>
      )}
    </>
  );
};

export default MainContent;
