parameters:
  - name: instructions
    type: string

jobs:
  - job: AcceptTest
    displayName: Confirm test acceptance before requesting production approval
    pool: server
    timeoutInMinutes: 1450
    steps:
      - task: ManualValidation@1
        timeoutInMinutes: 1440
        inputs:
          notifyUsers: ''
          approvers: '[ucdavis]\CAES Developers'
          allowApproversToApproveTheirOwnRuns: true
          instructions: ${{ parameters.instructions }}
          onTimeout: reject
