version: "3.8"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - playwright-cache:/root/.cache/ms-playwright
      - ./persistent_bash_history:/home/vscode/.bash_history
    command: sleep infinity
    ports:
      - "3001:3000" # use localhost:3001 to access the app from the host machine

  postgres:
    image: pgvector/pgvector:pg17
    container_name: pw-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: policywonk
    ports:
      - "5433:5432" # Maps container's PostgreSQL (5432) to host's 5433 (avoid conflicts)
    volumes:
      - ./pg_data:/var/lib/postgresql/data

volumes:
  playwright-cache:
  pg_data:
