version: "3.8"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - playwright-cache:/root/.cache/ms-playwright
    command: sleep infinity
    ports:
      - "3001:3000" # use localhost:3001 to access the app from the host machine

  postgres:
    image: postgres:17
    container_name: pw-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: policywonk
    ports:
      - "5433:5432" # Maps container's PostgreSQL (5432) to host's 5433 (avoid conflicts)
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  jackson: # for SAML SSO
    image: boxyhq/jackson
    container_name: pw-jackson
    restart: unless-stopped
    environment:
      DB_ENGINE: "sql"
      DB_TYPE: "postgres"
      DB_URL: "postgres://root:example@postgres:5432/policywonk"
      JACKSON_API_KEYS: "secret"
      NEXTAUTH_URL: "http://localhost:5225"
      EXTERNAL_URL: "http://localhost:5225"
      NEXTAUTH_SECRET: "super-secret"
      NEXTAUTH_ADMIN_CREDENTIALS: "admin@company.com:secretpassword"
      SAML_AUDIENCE: "https://policywonk.ucdavis.edu/shibboleth" #SP Entity ID
    ports:
      - "5225:5225"

volumes:
  playwright-cache:
  pg_data:
