"""add chat group

Revision ID: 1f0df76c49f9
Revises: bc221af58bd5
Create Date: 2025-05-08 22:11:56.765716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0df76c49f9'
down_revision: Union[str, None] = 'bc221af58bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # create a new column 'group' in the 'chats' table and default to ucdavis
    # once we've migrated, we'll remove the default so we need to set it in the future
    op.add_column('chats', sa.Column('group', sa.String(),
                  nullable=False, server_default='ucdavis'))
    # Remove the default for future inserts
    op.alter_column('chats', 'group', server_default=None)

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index('idx_group', 'chats', ['group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_group', table_name='chats')
    op.drop_column('chats', 'group')
    # ### end Alembic commands ###
