"""docs identity

Revision ID: 40e8eb8de8b2
Revises: d5b6aaeb712e
Create Date: 2025-03-06 21:43:41.799788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e8eb8de8b2'
down_revision: Union[str, None] = 'd5b6aaeb712e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add IDENTITY (autoincrement) to documents.id column
    op.execute(
        'ALTER TABLE documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY')


def downgrade() -> None:
    # Remove IDENTITY from documents.id column
    op.execute('ALTER TABLE documents ALTER COLUMN id DROP IDENTITY IF EXISTS')
