"""add upn to users

Revision ID: 7a55612dd058
Revises: 40e8eb8de8b2
Create Date: 2025-03-13 21:39:38.846868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a55612dd058'
down_revision: Union[str, None] = '40e8eb8de8b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('upn', sa.String(), nullable=False))
    op.alter_column('users', 'ms_user_id',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_constraint('users_ms_user_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_upn'), 'users', ['upn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_upn'), table_name='users')
    op.create_unique_constraint(
        'users_ms_user_id_key', 'users', ['ms_user_id'])
    op.alter_column('users', 'ms_user_id',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_column('users', 'upn')
    # ### end Alembic commands ###
