"""initial create

Revision ID: b83f8109ce65
Revises: 
Create Date: 2025-03-03 23:44:10.432049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83f8109ce65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('requires_sync', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('expected_output', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('ADMIN', 'USER', name='rolename', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('refresh_frequency', sa.Enum('DAILY', 'WEEKLY', name='refreshfrequency', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'FAILED', 'DEACTIVATE', name='sourcestatus', native_enum=False), nullable=False),
    sa.Column('type', sa.Enum('UCOP', 'UCDPOLICYMANUAL', 'UCCONTRACTS', 'RECURSIVE', 'SITEMAP', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('last_failed', sa.DateTime(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_refresh_status_last_updated', 'sources', ['refresh_frequency', 'status', 'last_updated'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('kerberos', sa.String(length=20), nullable=True),
    sa.Column('iam', sa.String(length=10), nullable=True),
    sa.Column('ms_user_id', sa.String(), nullable=False),
    sa.Column('titles', sa.String(), nullable=True),
    sa.Column('affiliations', sa.String(), nullable=True),
    sa.Column('departments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ms_user_id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_kerberos', 'users', ['kerberos'], unique=False)
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_table('assistant_collections',
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('assistant_id', 'collection_id')
    )
    op.create_index('ix_assistant_collections_assistant_id', 'assistant_collections', ['assistant_id'], unique=False)
    op.create_index('ix_assistant_collections_collection_id', 'assistant_collections', ['collection_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('assistant_slug', sa.String(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('share_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_slug'], ['assistants.slug'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_id_active', 'chats', ['id', 'active'], unique=False)
    op.create_index('idx_userid_active_timestamp', 'chats', ['user_id', 'active', 'timestamp'], unique=False)
    op.create_table('collections_sources',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'source_id')
    )
    op.create_index('ix_collections_sources_collection_id', 'collections_sources', ['collection_id'], unique=False)
    op.create_index('ix_collections_sources_source_id', 'collections_sources', ['source_id'], unique=False)
    op.create_table('default_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assistant_slug', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_slug'], ['assistants.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_url'), 'documents', ['url'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_version', sa.String(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('run_date', sa.DateTime(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', 'INPROGRESS', name='indexstatus', native_enum=False), nullable=False),
    sa.Column('num_docs_indexed', sa.Integer(), nullable=False),
    sa.Column('num_new_docs', sa.Integer(), nullable=False),
    sa.Column('num_docs_removed', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('prompt_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('actual_output', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_evaluations')
    op.drop_table('user_roles')
    op.drop_table('index_attempts')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_documents_url'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('default_questions')
    op.drop_index('ix_collections_sources_source_id', table_name='collections_sources')
    op.drop_index('ix_collections_sources_collection_id', table_name='collections_sources')
    op.drop_table('collections_sources')
    op.drop_index('idx_userid_active_timestamp', table_name='chats')
    op.drop_index('idx_id_active', table_name='chats')
    op.drop_table('chats')
    op.drop_index('ix_assistant_collections_collection_id', table_name='assistant_collections')
    op.drop_index('ix_assistant_collections_assistant_id', table_name='assistant_collections')
    op.drop_table('assistant_collections')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_index('ix_users_kerberos', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_source_refresh_status_last_updated', table_name='sources')
    op.drop_table('sources')
    op.drop_table('roles')
    op.drop_table('prompts')
    op.drop_table('collections')
    op.drop_table('assistants')
    # ### end Alembic commands ###
