"""remove docchunks

Revision ID: f575d8ae25af
Revises: 1f0df76c49f9
Create Date: 2025-12-16 23:14:02.931394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f575d8ae25af'
down_revision: Union[str, None] = '1f0df76c49f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('document_chunks_embedding_idx',
                  table_name='document_chunks', postgresql_using='hnsw')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('document_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('chunk_index', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('chunk_text', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('embedding', sa.NullType(),
                              autoincrement=False, nullable=False),
                    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['document_id'], ['documents.id'], name='document_chunks_document_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='document_chunks_pkey')
                    )
    op.create_index('document_chunks_embedding_idx', 'document_chunks', [
                    'embedding'], unique=False, postgresql_using='hnsw')
    # ### end Alembic commands ###
